# Generated by Django 2.2.5 on 2019-10-04 13:03
from django.db import migrations, models

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=10)),
                ('LastName', models.CharField(max_length=10)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=10)),
                ('Pincode', models.IntegerField(max_length=10)),
                ('Mobile_no', models.IntegerField(max_length=10)),
                ('Email', models.TextField()),
            ],
        ),
    ]
