# Generated by Django 2.2.5 on 2019-10-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='Mobile_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='form',
            name='Pincode',
            field=models.IntegerField(),
        ),
    ]
