# Generated by Django 2.2.5 on 2019-10-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_auto_20191004_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecieverName', models.CharField(max_length=10)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=10)),
                ('Pincode', models.IntegerField()),
                ('IType', models.CharField(max_length=15)),
                ('Item_weight', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.RenameField(
            model_name='form',
            old_name='Mobile_no',
            new_name='Mobile_No',
        ),
    ]
