# Generated by Django 2.2.5 on 2019-10-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0003_auto_20191015_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sform',
            name='Item_weight',
            field=models.IntegerField(),
        ),
    ]
