# Generated by Django 2.2.5 on 2019-10-15 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0004_auto_20191015_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sform',
            old_name='IType',
            new_name='Itype',
        ),
    ]
